### ISSUE TITLE
RubyMine steals focus when switching windows quickly

### ISSUE THREAD

**Issue by radnan** [basgren/railways#17] opened 2015-03-16 08:05 UTC
https://youtrack.jetbrains.com/issue/RUBY-16411

## What steps will reproduce the problem?

1. Click on "Routes" to run `rake:routes` to initialize route lookup table.
2. Switch to a different application window
3. Switch to RubyMine (using mouse or ALT+TAB) and then **quickly** switch back to the other application window
4. RubyMine will now steal window focus

## What is the expected result?
RubyMine should not steal focus since the user actively switched to a different application window.

## What happens instead?
RubyMine steals the window focus. If you happen to start typing anything it'll show up in the RubyMine editor instead.

## Please provide any additional information below.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:  Ubuntu
Description:     Ubuntu 14.04.2 LTS
Release:         14.04
Codename:        trusty
```

```
$ java -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
```

**Comment by basgren** [comment] 2015-03-16 23:06
Thank you for the report. Unfortunately, I was unable to reproduce this issue.
Maybe a stupid question, but did you try to disable plugin and reproduce this issue?
Thanks.

**Comment by radnan** [comment] 2015-03-17 09:20
Not a stupid question, I already tried that. That's how I pinpointed the issue to this plugin :)

**Comment by basgren** [comment] 2015-05-16 21:30
Finally it seems that I could reproduce this issue :) But also I could reproduce this for all other tool windows of the IDE. When you open any tool window and then switch to a different application, IDE steals focus as soon as the tool window is initialized and displayed. Maybe for Railways it's more noticeable as it takes more time to initialize and load routes.
I'm closing the issue, as I doubt this is something that can be done at the Railways side.
Thank you!

**Closed by basgren** 2015-05-16 21:30 UTC
